services:
  - type: web
    name: travel-together
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn travel_together.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.0